config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places
  resources :categories, only: [:show, :index]
  resources :votes, only: [:create, :destroy]

  resources :places do
       resources :comments, only: [:create, :destroy]
       resources :votes, only: [:create, :destroy]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :body, length: {minimum: 5}
  belongs_to :place
  belongs_to :customer

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments, dependent: :destroy
  has_many :votes

  before_destroy :assign_to_first_user

    private

      def assign_to_first_user
            places.update_all(customer_id: Customer.first.id)
      end
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :category

  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :place
  belongs_to :customer

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :load_sidebar_categories
   def load_sidebar_categories
      @sidebar_categories = Category.all
      end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category= Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_place
  before_action :set_comment, only: [:destroy]
  before_action :authorize_customer!, only: [:destroy]

  def create
    @comment = @place.comments.new(comment_params)

    @comment.customer= current_customer
       if @comment.save
               redirect_to @place, notice: "Comment was saved"
              else
                       redirect_to @place, notice: "Comment couldn't saved"
                     end
  end

  def destroy
    @comment.destroy
       redirect_to @place, notice: "Comment was deleted"
  end


  private
  def set_comment
        @comment = Comment.find(params[:id])
      end

    def authorize_customer!
        redirect_to @place, notice: "Not authorized" unless @comment.customer_id == current_customer_id
      end


  def comment_params
        params.require(:comment).permit(:body)
      end

    def set_place
        @place= Place.find(params[:place_id])
     end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_customer!, except: [:show, :index]
  before_action :set_place, only: [:show, :update, :edit, :destroy]
  before_action :authorize_customer!, only: [:edit, :update, :destroy]


  def new
    @place=Place.new
    load_categories

  end
  def index
    @places=Place.all
  end

  def show

  end

  def create
    @place = current_customer.places.new(place_params)
    if @place.save
      flash[:success]='İşlem başarıyla tamamlandı!'
      redirect_to place_path(@place)
    else
      load_categories
      render :new
    end
  end

  def edit
    load_categories

  end

  def update
    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      load_categories
      render :edit
    end

  end

  def destroy
    @place.destroy
    redirect_to place_path, notice: "Place was deleted"
  end

  private

  def authorize_customer!
    redirect_to root_path, notice: "Not authorized" unless @place.customer_id == current_user.id
  end

  def load_categories
    @categories = Category.all.collect {|c| [c.name, c.id ] }
  end

  def set_place
    @place=Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :adress, :phone_number, :contact_mail, :established_at, :city, :description , :category_id)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_place

  def create
    #@vote = @idea.votes.new(rating: params[:vote][:rating])
  end

  def destroy
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/application/_flash.html.erb
<% if !flash.empty? %>
    <div id="flash">
      <% flash.keys.each do |k| %>
          <div class="alert alert-warning" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            <%= flash[k] %>
          </div>
      <% end %>
    </div>
<% end %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<% @categories.each do |c| %>
    <%= link_to c.name, category_path(c) %><br />
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% @category.places.each do |place| %>
    <b>ID </b><%= place.id %>
    <b>Name </b>
    <%= link_to place.name, place_path(place) %>

<% end %>

app/views/comments/_comment_list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Comments
  </div>
  <div class="panel-body">
    <% @place.comments.each do |comment| %>
        <small><%= comment.customer.email %> says:</small>
        <p>
          <%= comment.body %>
          <% if current_customer.present? && comment.customer_id == current_customer.id %>
              <small><%= link_to "Delete", place_comment_path(@place, comment), method: :delete %></small>
          <% end %>
        </p>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<% if current_customer.present? %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        Send a new comment
      </div>
      <div class="panel-body">
        <%= form_for [@place, @place.comments.build] do |f| %>
            <%= f.text_area :body, rows: 5 %><br>
            <%= f.submit 'Send' %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Place Project</title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600&subset=latin,latin-ext" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav id="navbar-top" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Fikrim Geldi!", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active">
                          <%= link_to "New Place", new_place_path %>
                     </li>
        <% if current_customer.present? %>
            <li><a href="#"><%= current_customer.email %></a></li>
            <li><%= link_to "Logout", destroy_customer_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Login", new_customer_session_path %></li>
            <li><%= link_to "Register", new_customer_registration_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>



<% if params[:controller] == 'ideas' and params[:action] == 'index' %>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="<%= asset_url 'slider/slide_1.jpg' %>" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Lorem Ipsum Nedir?</h1>
              <p>Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Hemen Kayıt Ol!</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="<%= asset_url 'slider/slide_2.jpg' %>" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Nereden Gelir?</h1>
              <p>Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. </p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Hemen Kayıt Ol</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNUX5fwHwAEbwI2Qne/HAAAAABJRU5ErkJggg==" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Neden Kullanırız?</h1>
              <p>Yinelenen bir sayfa içeriğinin okuyucunun dikkatini dağıttığı bilinen bir gerçektir. Lorem Ipsum kullanmanın amacı, sürekli 'buraya metin gelecek, buraya metin gelecek' yazmaya kıyasla daha dengeli bir harf dağılımı sağlayarak okunurluğu artırmasıdır.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Hemen Kayıt Ol!</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="fa fa-angle-left fa-2x" aria-hidden="true"></span>
        <span class="sr-only">Önceki</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="fa fa-angle-right fa-2x" aria-hidden="true"></span>
        <span class="sr-only">Sonraki</span>
      </a>
    </div><!-- /.carousel -->
<% end %>

<div id="main_container" class="container">

  <%= render "flash" %>

  <div class="row">
    <div class="col-md-9">
      <%= yield %>
    </div>
    <div id="navbar-right" class="col-md-3">
      <div class="nav-section">
        <h3>Arama Yap</h3>
        <form action="" class="search-form">
          <div class="input-group stylish-input-group">
            <input type="text" class="form-control"  placeholder="Fikir Bul!" >
            <span class="input-group-addon">
                            <button type="submit">
                                <span class="fa fa-search"></span>
                            </button>
                        </span>
          </div>
        </form>
      </div>
      <div id="categories" class="nav-section">
        <h3>Kategoriler</h3>

        <% @sidebar_categories.each do |c| %>
            <%= link_to category_path(c) do %>
                <i class="fa fa-angle-right"></i>
                <%= c.name %>
            <% end %>
        <% end %>

      </div>
      <div id="tags" class="nav-section">
        <h3>Etiketler</h3>
        <a href="#" class="label label-default">Etiket 1</a>
        <a href="#" class="label label-default">Etiket 2</a>
        <a href="#" class="label label-default">Etiket 3</a>
        <a href="#" class="label label-default">Etiket 4</a>
        <a href="#" class="label label-default">Etiket 5</a>
        <a href="#" class="label label-default">Etiket 6</a>
        <a href="#" class="label label-default">Etiket 7</a>
        <a href="#" class="label label-default">Etiket 4</a>
      </div>
    </div>
  </div>
</div>

<footer class="footer">
  <div class="container">
    <div class="pull-left">
      <p class="text-muted">Bu tasarım GPL v3 Lisansıyla Kamuya Hediye Edilmiştir :)</p>
    </div>
    <div class="pull-right">
      <p class="text-muted">
        <a href="#"> <i class="fa fa-facebook-square fa-2x"></i> </a>
        <a href="#"> <i class="fa fa-twitter-square fa-2x"></i> </a>
      </p>
    </div>
  </div>
</footer>


<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>

</body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |p| %>
    <%= p.label :name %> <br>
    <%= p.text_field :name, placeholder: 'Name', class: "form-control input-sm" %><br>
    <br>
    <%= p.label :adress %>
    <br>
    <%= p.text_area :adress, placeholder: 'Address' %><br>
    <br>
    <%= p.label :established_at %>
    <br>
    <%= p.date_select :established_at, placeholder: 'Established At' %><br>
    <br>
    <%= p.label :phone_number %> <br>
    <%= p.text_field :phone_number, placeholder: 'Phone Number' %><br>
    <br>
    <%= p.label :contact_mail %> <br>
    <%= p.text_field :contact_mail, placeholder: 'Contact Mail' %><br>
    <br>
    <%= p.label :city %> <br>
    <%= p.text_field :city, placeholder: 'City' %><br>
    <br>
    <%= p.label :description %> <br>
    <%= p.text_area :description, placeholder: 'Description' %><br>
    <br>

    <%= p.select :category_id, @categories %>


    <%= p.submit 'Send' %>
<% end %>

app/views/places/edit.html.erb
<h1>Editing <%= @place.name %></h1>

<% if @place.errors.any? %>
    <h3>
      <%= @place.errors.full_messages.join(", ") %>
    </h3>
<% end %>

<%= render partial: "form" %>

app/views/places/index.html.erb
<% @places.each do |place| %>
    <b>ID:</b><%= place.id %>
    <b>Name: </b><%= link_to place.name, place_path(place) %>
    <b>Address: </b><%= place.adress %>
    <b>Phone Number: </b><%= place.phone_number %>
    <b>Contact Mail: </b><%= place.contact_mail %>
    <b>Established: </b><%= place.established_at %>
    <b>Description: </b><%= place.description %>
    <b>Category: </b><%= place.category.name unless place.category.nil? %>


    <br><br>

<% end %>

app/views/places/new.html.erb
<h1>Create a new Place</h1>

<% if @place.errors.any? %>
    <h3>
      <%= @place.errors.full_messages.join(" , ") %>
    </h3>
<% end %>

<%= render "form" %>

app/views/places/show.html.erb
Display Place<br /><br />

<b>ID:  </b><%= @place.id %><br />
<b>Name:  </b><%= @place.name %><br />
<b>Address: </b><%= @place.adress %><br />
<b>Phone Number: </b><%= @place.phone_number %><br />
<b>Contact Mail: </b><%= @place.contact_mail %><br />
<b>Established At: </b><%= @place.established_at %><br />
<b>City: </b><%= @place.city %><br />
<b>Description: </b><%= @place.description %><br />
<b>Category: </b><%= @place.category.name%> <br/>
<b>Customer: </b><%= @place.customer.email %> | <%= @place.customer.id %><br />


<br /><br /><br />

<%= render 'votes/form' %>
<%= render 'comments/comment_list' %>
<%= render 'comments/form' %>
<br/><br/>
<%= link_to "Back to idea list", places_path %>
<br/>
<% if current_customer.present? and current_customer.id == @place.customer_id %>
      <br/>
      <%= link_to "Edit idea", edit_place_path(@place) %>
     <br/>
      <%= link_to "Sil", place_path(@place), method: :delete %>
    <% end %>

app/views/votes/_form.html.erb
<%= form_for [@place, @place.votes.build] do |f| %>
    <% 5.times do |i| %>
        <%= f.radio_button :rating, i+1 %>
        <% (i+1).times do %>
            <i class='fa fa-star'></i>
        <% end %>
        <br />
    <% end %>

    <%= f.submit "Vote", class: "btn btn-sm btn-primary" %>
<% end %>